In [6]:
import requests, bs4
import pandas as pd
from lxml import html
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus, unquote
import requests
import json
import pandas as pd

#API KEY
my_key = 'cbp8333o530rtbb44j50jce00r3occ8t'

# 샘플 url 변형해서 사용

endpoint=f"https://open.jejudatahub.net/api/proxy/5D5a577taba7tbb71at1b1bt9tatata9/{my_key}?startDate=201601&endDate=201902&number=99"

#api 호출
resp=requests.get(endpoint)
print(resp.status_code)
print(resp.text)

#joson 파일로 가져왔기때문에, json() 함수로 data에 넣어주기
data=resp.json()

resp

import pandas as pd
from pandas.io.json import json_normalize
dfdata=pd.json_normalize(data['data'])
dfdata

200
{"totCnt":19573,"hasMore":true,"data":[{"sido":"제주도","sigungu":"제주시","cityGubun":"도심","marketType":"교통","userType":"제주도민","ageGroup":"60대이상","gender":"남","dtYearMonth":"201811","userCount":6662,"useCount":10306,"useCost":852676412},{"sido":"제주도","sigungu":"제주시","cityGubun":"도심","marketType":"교통","userType":"제주도민","ageGroup":"50대","gender":"여","dtYearMonth":"201811","userCount":6308,"useCount":8833,"useCost":530326171},{"sido":"제주도","sigungu":"제주시","cityGubun":"도심","marketType":"교통","userType":"제주도민","ageGroup":"50대","gender":"남","dtYearMonth":"201811","userCount":9898,"useCount":15206,"useCost":961645909},{"sido":"제주도","sigungu":"제주시","cityGubun":"도심","marketType":"교통","userType":"제주도민","ageGroup":"40대","gender":"여","dtYearMonth":"201811","userCount":7318,"useCount":10340,"useCost":519719592},{"sido":"제주도","sigungu":"제주시","cityGubun":"도심","marketType":"교통","userType":"제주도민","ageGroup":"40대","gender":"남","dtYearMonth":"201811","userCount":10610,"useCount":16201,"useCost":952902744},{"sido":"제주도","sigungu":"제주시","cityGubun":"도심","marketType":"교통","userType":"제주도민","ageGroup":"30대","gender":"여","dtYearMonth":"201811","userCount":5071,"useCount":6815,"useCost":318396395},{"sido":"제주도","sigungu":"제주시","cityGubun":"도심","marketType":"교통","userType":"제주도민","ageGroup":"30대","gender":"남","dtYearMonth":"201811","userCount":7307,"useCount":10405,"useCost":503344771},{"sido":"제주도","sigungu":"제주시","cityGubun":"도심","marketType":"교통","userType":"제주도민","ageGroup":"20대미만","gender":"여","dtYearMonth":"201811","userCount":27,"useCount":31,"useCost":1804602},{"sido":"제주도","sigungu":"제주시","cityGubun":"도심","marketType":"교통","userType":"제주도민","ageGroup":"20대미만","gender":"남","dtYearMonth":"201811","userCount":64,"useCount":73,"useCost":1974897},{"sido":"제주도","sigungu":"제주시","cityGubun":"도심","marketType":"교통","userType":"제주도민","ageGroup":"20대","gender":"여","dtYearMonth":"201811","userCount":2377,"useCount":2980,"useCost":121159916}]}

,sido,sigungu,cityGubun,marketType,userType,ageGroup,gender,dtYearMonth,userCount,useCount,useCost
0,제주도,제주시,도심,교통,제주도민,60대이상,남,201811,6662,10306,852676412
1,제주도,제주시,도심,교통,제주도민,50대,여,201811,6308,8833,530326171
2,제주도,제주시,도심,교통,제주도민,50대,남,201811,9898,15206,961645909
3,제주도,제주시,도심,교통,제주도민,40대,여,201811,7318,10340,519719592
4,제주도,제주시,도심,교통,제주도민,40대,남,201811,10610,16201,952902744
5,제주도,제주시,도심,교통,제주도민,30대,여,201811,5071,6815,318396395
6,제주도,제주시,도심,교통,제주도민,30대,남,201811,7307,10405,503344771
7,제주도,제주시,도심,교통,제주도민,20대미만,여,201811,27,31,1804602
8,제주도,제주시,도심,교통,제주도민,20대미만,남,201811,64,73,1974897
9,제주도,제주시,도심,교통,제주도민,20대,여,201811,2377,2980,121159916

In [5]:
dfdata.to_csv("carddata.csv")